Thank THE LINK TO MY GITHUB REPO IS :
    

In [1]:
#Importing all the required libraries
import numpy as np 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

1.(10 Points) Write a Python/NumPy code block that creates a new array containing only one instance of any item that 
appears within all three of these arrays: 

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 


b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) 


c = np.array([12, 8, 3, 7, 4, 1, 2, 9, 3, 4]) 


Your output should contain only the unique overlapping values. For example, if a 2 is found in arrays a, b and c, your 
output should contain only one 2 even if any of the arrays contains more than one 2 within it. 

In [2]:
#Initializing the arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

c = np.array([12, 8, 3, 7, 4, 1, 2, 9, 3, 4])

In [3]:
#Using intersect1d function for finding the intersection of the arrays a and b
d=np.intersect1d(a,b)

In [4]:
#Using intersect1d function for finding the intersection of the arrays d and c
d=np.intersect1d(d,c)

In [5]:
#Displaying the array d 
d

array([2, 4])

2.(10 Points) Create the following 3x6 array using knowledge you have of Python’s / NumPy’s  sequencing functionality 
so that you do not need to explicitly key in every integer value. 

1 4 7 10 13 16 
2 5 8 11 14 17 
3 6 9 12 15 18 


In [6]:
#Using arange and Transpose to find the answer
x=(np.arange(1,19).reshape(6,3)).T

In [7]:
#Displaying the resulting array
x

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

3.(10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as 
“flattening”. Transform the 3x6 array shown above in Problem 2 into a unidimensional array such that the sequence of 
values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 
 

In [8]:
#Flattening the array and storing in y 
y=x.T.flatten()

In [9]:
#Displaying y 
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

4.(15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional NumPy array 

In [10]:
#Displaying the array to reshape
x

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [11]:
#Reshaping the array to 3D
x.reshape(2,3,3)

array([[[ 1,  4,  7],
        [10, 13, 16],
        [ 2,  5,  8]],

       [[11, 14, 17],
        [ 3,  6,  9],
        [12, 15, 18]]])

5.(15 Points) Transform the 3-D array you created in Problem 4 back to the 3x6  2-dimensional format shown in 
Problem 2. 

In [12]:
#Reshaping the 3D array back to 3X6
x.reshape(3,6)

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

6.(10 Points) You are given the following three arrays: 

a = np.array([12, 5, 7, 15, 3, 1, 8, 9, 2]) 

b = np.array([14, 2, 6, 3, 11, 19, 9, 12, 5]) 

c = np.array([1, 12, 4, 3, 13, 1, 9, 12, 5, 7]) 

Write a Python/Numpy code block that removes from array a any items that are also present in either array b or array c. 

In [13]:
#Initializing the arrays 
a = np.array([12, 5, 7, 15, 3, 1, 8, 9, 2])

b = np.array([14, 2, 6, 3, 11, 19, 9, 12, 5])

c = np.array([1, 12, 4, 3, 13, 1, 9, 12, 5, 7])

In [14]:
#Creating a function 
def remove(a,b,c) :
    '''A function that takes 3 inputs and returns an list having the values that are not present in the tow other arrays that are passed '''
    d=set(a)-set(b)-set(c)
    return list(d)

In [15]:
#Printing the output after running the fucntion
print((remove(a,b,c)))

[8, 15]


7.(30 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a 
NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.

The original source of the data set contains an overview of its content:  

https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m 

Scroll down to the bottom of that page to access the interactive data viewer that includes the column headings for the 
data.  Once you are comfortable in your understanding of the various data attributes, get started on the assignment as 
follows: 

1) Load the provided M6_Data.csv file to your online AIM 5001 Github Repository.  

2) Then, from within your M6 Assignment Jupyter Notebook, read the data set from your Github repository and load it into a Pandas dataframe using the code snippet provided below.  ** Please note that you will need to replace the 'link_to_raw_copy of data file in your Github Repository placeholder shown below with a link to the “raw” version of the file you pushed to your online GitHub repository. ** 


Copy the following small Python code snippet into your Jupyter Notebook: 

In [16]:
import pandas 
import numpy as np 
 
# supress scientific notation 
np.set_printoptions(suppress = True) 
 
# read the data file from GitHub and convert to a NumPy ndarray object 
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below 
# with a link to the “raw” version of the file you pushed to your online GitHub repository 
 
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/KenK99/AIM5002-Reiyo/main/Module6_Data.csv').to_numpy() 
 
# verify you have an ndarray object 
type(nyc_water) 

numpy.ndarray

This code will read the contents of the provided data file into a NumPy ndarray object. Execute the code within your 
Jupyter Notebook. If successful, the output of the type(nyc_water) function should be: numpy.ndarray 
Using the nyc_water array you’ve created, answer the following questions using NumPy’s indexing, slicing, methods, and 
functions: 

 Which year had the minimum population amount? 

 
 Add a new column to the numpy array containing the total annual water consumption for the city (in millions 
of gallons of water and assuming a 365 day calendar year).  
 
 
 What is the median and the variance of the NYC daily water consumption metric? 

 
 What is the increase or decrease in total annual water consumption from year to year?  (HINT: Your output 
should include the calculation of a data value for every year represented within the data set except for the first 
year). 

Please note that it may take a bit of time for Jupyter to load the data set from your GitHub repository.  You will know 
that process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the 
notebook.

In [17]:
#Displying the numpy array
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

 Which year had the minimum population amount?

In [18]:
#Assing the column values to temporary list variables
water=nyc_water[:,1]
year=nyc_water[:,0]
#Storing the mininum water consumption in x 
x=water.min()
#Looping to find the index position of the minimum consuption and printing the year at the same index position
for i in range(len(water)):
    if water[i]==x :
        print('Year : ',year[i])

Year :  1980.0


 Add a new column to the numpy array containing the total annual water consumption for the city (in millions of gallons of water and assuming a 365 day calendar year).

In [19]:
#Calculating the annual water consuption and inserting the created numpy array to nyc_water
calc = nyc_water[:,2]*365/1000000
nyc_water=np.insert(nyc_water,4,calc,axis=1)

In [20]:
#Displying the numpy array
nyc_water

array([[   1979.       , 7102100.       ,    1512.       ,
            213.       ,       0.55188  ],
       [   1980.       , 7071639.       ,    1506.       ,
            213.       ,       0.54969  ],
       [   1981.       , 7089241.       ,    1309.       ,
            185.       ,       0.477785 ],
       [   1982.       , 7109105.       ,    1382.       ,
            194.       ,       0.50443  ],
       [   1983.       , 7181224.       ,    1424.       ,
            198.       ,       0.51976  ],
       [   1984.       , 7234514.       ,    1465.       ,
            203.       ,       0.534725 ],
       [   1985.       , 7274054.       ,    1326.       ,
            182.       ,       0.48399  ],
       [   1986.       , 7319246.       ,    1351.       ,
            185.       ,       0.493115 ],
       [   1987.       , 7342476.       ,    1447.       ,
            197.       ,       0.528155 ],
       [   1988.       , 7353719.       ,    1484.       ,
            202.       

 What is the median and the variance of the NYC daily water consumption metric?



In [21]:
#Displying the median 
np.median(nyc_water[:,2])

1237.2

In [22]:
np.var(nyc_water[:,2])

29744.87353057199

 What is the increase or decrease in total annual water consumption from year to year? (HINT: Your output should include the calculation of a data value for every year represented within the data set except for the first year).

Please note that it may take a bit of time for Jupyter to load the data set from your GitHub repository. You will know that process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the notebook.

In [23]:
x_indec_water=[]
x_indec_water.append(0)


In [24]:
for i in range(1,len(nyc_water[:,4])):
        x_indec_water.append((nyc_water[:,4][i]-nyc_water[:,4][i-1]))

In [25]:
x_indec_water=np.array(x_indec_water)

In [26]:
x_indec_water

array([ 0.       , -0.00219  , -0.071905 ,  0.026645 ,  0.01533  ,
        0.014965 , -0.050735 ,  0.009125 ,  0.03504  ,  0.013505 ,
       -0.02993  ,  0.00803  ,  0.016425 , -0.0365   , -0.0001825,
       -0.003942 , -0.01168  , -0.010147 , -0.033726 ,  0.00511  ,
        0.0064605,  0.001168 , -0.020586 , -0.017666 , -0.0152935,
        0.002117 ,  0.0140525, -0.025185 ,  0.016425 , -0.00584  ,
       -0.0330325,  0.0114975, -0.00657  , -0.0043435, -0.001095 ,
       -0.0036865,  0.004745 , -0.002555 , -0.004307 ])